### ISSUE TITLE
矢量瓦片-优化

### ISSUE THREAD

**Issue by wjtwy** [fuzhenn/examples.maptalks.com#17]
- [x]  [1、矢量瓦片-点的样式-组合多个图标：示例看不出来是2个图标 ](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056779456)
- [x] [2、矢量瓦片-点的样式-组合图标和文字：更换示例](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056786868)
- [x] [3、矢量瓦片-点的样式-文字随地图级别缩放大小：将文字mt改成大写MT](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056792903)
- [x] [4、矢量瓦片-点的样式-跟随地图倾斜/旋转的图标和文字: 增加文字](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056851835)
- [x] [5、矢量瓦片-点的样式- 跟随地图旋转的图标和文字:  更改代码](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056853439)
- [x] [6、矢量瓦片-点的样式- 不同属性显示不同的图标: 更换水滴尺寸和颜色](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056857075)
- [x] [7、矢量瓦片-点的样式- 从属性数据中读取文字:将文字字号改成20](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056860253)
- [x] [8、矢量瓦片-线的样式-沿线绘制文字： 将文字的字号改成15](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056883352)
- [x] [9、矢量瓦片-面的样式： 去掉纹理动画和设置高度](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056885854)
- [x] [10、矢量瓦片-面的样式-在面上绘制文字： 将文字尺寸改成15px](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1056887586)
- [x] [11、矢量瓦片-三维面的样式-高度和侧面设置不同纹理： 更换示例](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1057011561)
- [x] [12、矢量瓦片-面的水面效果： 3个词条的示例更换成下图msd](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1057025039)
- [x]  [13、矢量瓦片-面的水面效-水面上绘制文字： 文字要修改](https://github.com/fuzhenn/examples.maptalks.com/issues/17#issuecomment-1057029358)
