### ISSUE TITLE
矢量瓦片-优化

### ISSUE THREAD

**Issue by wjtwy** [fuzhenn/examples.maptalks.com#28]
- [x] [1、矢量瓦片-点的样式-图标随地图级别缩放大小：修改代码](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057652412)
- [x] [2、矢量瓦片-点的样式- 不同属性显示不同的图标: 把水滴颜色改成ff8a00](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057654029)
- [x] [3、矢量瓦片-图层交互-高亮所有数据+高亮指定渲染插件数据 更换示例地图颜色](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057743076)
- [x] [4、矢量瓦片-图层交互-更改红圈内示例数据颜色](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057747695)
- [x] [5、矢量瓦片-图层交互-红圈内2个示例增加交互](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057755154)
- [x] [6、矢量瓦片-图层交互-鼠标点选数据 增加交互](https://github.com/fuzhenn/examples.maptalks.com/issues/28#issuecomment-1057758012)
